### ISSUE TITLE
问一下大佬

### ISSUE THREAD

**Issue by chenjie-dev** [penguin806/HunnuStuInfoLookupTool#1]
偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研

**Comment by penguin806** [comment]
> 
> 
> 偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研

你好，我觉得应该都不错。
其他老师我不了解，我的导师，学术能力强，而且特别为学生考虑，跟他学到了很多，非常感激。我认为能遇到一位这样的老师是人生最幸运的事之一。

**Comment by chenjie-dev** [comment]
> > 偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研
> 
> 你好，我觉得应该都不错。
> 其他老师我不了解，我的导师，学术能力强，而且特别为学生考虑，跟他学到了很多，非常感激。我认为能遇到一位这样的老师是人生最幸运的事之一。

请问是哪位老师啊，想了解一下

**Comment by penguin806** [comment]
> 
> 
> > > 偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研
> > 
> > 
> > 你好，我觉得应该都不错。
> > 其他老师我不了解，我的导师，学术能力强，而且特别为学生考虑，跟他学到了很多，非常感激。我认为能遇到一位这样的老师是人生最幸运的事之一。
> 
> 请问是哪位老师啊，想了解一下

钟坚成教授

**Comment by chenjie-dev** [comment]
> > > > 偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研
> > > 
> > > 
> > > 你好，我觉得应该都不错。
> > > 其他老师我不了解，我的导师，学术能力强，而且特别为学生考虑，跟他学到了很多，非常感激。我认为能遇到一位这样的老师是人生最幸运的事之一。
> > 
> > 
> > 请问是哪位老师啊，想了解一下
> 
> 钟坚成教授

谢谢！

**Comment by penguin806** [comment]
> 
> 
> > > > > 偶然路过，问问大佬，湖南师范计算机老师怎么样呀，想考贵校的研
> > > > 
> > > > 
> > > > 你好，我觉得应该都不错。
> > > > 其他老师我不了解，我的导师，学术能力强，而且特别为学生考虑，跟他学到了很多，非常感激。我认为能遇到一位这样的老师是人生最幸运的事之一。
> > > 
> > > 
> > > 请问是哪位老师啊，想了解一下
> > 
> > 
> > 钟坚成教授
> 
> 谢谢！

不客气~
